name: blueprint

services:
  database:
    image: postgres:17
    mem_limit: 512m
    mem_reservation: 64m
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default
    container_name: blueprint-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "3000:3000"
    mem_limit: 1024m
    mem_reservation: 128m
    expose:
      - 3000
    tty: true
    environment:
      - NODE_ENV=production
    networks:
      - default
    container_name: blueprint-server
    depends_on:
      - database
    volumes:
      - /apps/server
      - /apps/node_modules

networks:
  default:
    name: blueprint-network
    external: true